# -*- coding: utf-8 -*-
"""Data Analyst_Kel_Traveloka.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/157ExVgQydwSRd73ZGh_qNU8ovHjtlavO
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)

file_excel = 'data_traveloka_200_playstore.xlsx'

df_kuesioner = pd.read_excel(file_excel, sheet_name='Data_Kuesioner_Form')
df_playstore = pd.read_excel(file_excel, sheet_name='Data_Playstore_200')

print("=== STATUS LOAD DATA ===")
print("Data Kuesioner berhasil dimuat, bentuk:", df_kuesioner.shape)
print("Data Playstore berhasil dimuat, bentuk:", df_playstore.shape)

"""# Grafik Heatmap Korelasi (Data Kuesioner)"""

df_skala = df_kuesioner.iloc[:, 5:]

singkatan = [f"P{i+1}" for i in range(df_skala.shape[1])]
df_korelasi = df_skala.copy()
df_korelasi.columns = singkatan

plt.figure(figsize=(11, 9))
sns.heatmap(df_korelasi.corr(), annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title('Matriks Korelasi Kepuasan Pengguna Traveloka (Skala Kuesioner)', fontsize=14, pad=15)
plt.tight_layout()
plt.show()

print("=== KETERANGAN SINGKATAN PERTANYAAN ===")
for sing, asli in zip(singkatan, df_skala.columns):
    print(f"{sing}: {asli[:85]}...")

"""# Segmentasi Fitur PayLater Berdasarkan Kelompok Usia (Data Kuesioner)"""

kolom_paylater = [col for col in df_kuesioner.columns if 'PayLater' in col or 'paylater' in col.lower()]

if kolom_paylater:
    target_kolom = kolom_paylater[0]

    ct = pd.crosstab(df_kuesioner['Usia '], df_kuesioner[target_kolom], normalize='index') * 100

    ct.plot(kind='bar', stacked=True, cmap='RdYlGn', edgecolor='black', figsize=(10, 6))
    plt.title('Distribusi Pengaruh Fitur PayLater Berdasarkan Kelompok Usia', fontsize=14, pad=15)
    plt.xlabel('Kelompok Usia Responden')
    plt.ylabel('Persentase Pilihan (%)')
    plt.xticks(rotation=15, ha='right')
    plt.legend(title='Skala Nilai', bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.tight_layout()
    plt.show()
else:
    print("[Peringatan] Kolom bertema 'PayLater' tidak ditemukan di data kuesioner.")

"""# Kategori Keluhan Utama pada Rating Buruk (Data Playstore)"""

df_rating_rendah = df_playstore[df_playstore['rating'].isin([1, 2])]

order_keluhan = df_rating_rendah['kategori keluhan'].value_counts().index

plt.figure(figsize=(10, 6))
sns.countplot(data=df_rating_rendah, y='kategori keluhan', order=order_keluhan, palette='Reds_r')
plt.title('Kategori Keluhan Utama pada Rating Buruk (Rating 1 & 2) di Playstore', fontsize=14, pad=15)
plt.xlabel('Jumlah Ulasan / Keluhan')
plt.ylabel('Kategori Keluhan')
plt.tight_layout()
plt.show()

"""# Distribusi Rating per Kategori Keluhan (Data Playstore)"""

pivot_rating_keluhan = pd.crosstab(df_playstore['kategori keluhan'], df_playstore['rating'])

pivot_rating_keluhan['Total'] = pivot_rating_keluhan.sum(axis=1)
pivot_rating_keluhan = pivot_rating_keluhan.sort_values(by='Total', ascending=False).drop(columns='Total')

pivot_rating_keluhan.plot(kind='bar', figsize=(12, 6), width=0.8, cmap='viridis')
plt.title('Distribusi Rating (1 - 5) pada Setiap Kategori Keluhan di Playstore', fontsize=14, pad=15)
plt.xlabel('Kategori Keluhan')
plt.ylabel('Jumlah Respon / Review')
plt.xticks(rotation=30, ha='right')
plt.legend(title='Rating Bintang', loc='upper right')
plt.tight_layout()
plt.show()